# Generated by Django 5.1.2 on 2024-12-20 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pie',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pie',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pie',
            name='baker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pie',
            name='crust',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
