# Generated by Django 5.1.2 on 2024-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piesapp', '0002_remove_pie_created_at_pie_votes_alter_pie_baker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='filling',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
